In [1]:
# tensorflow 基础
!ls ../data

1-s2.0-S0167732222024916-mmc1.docx
amino_acids_hydrate_data.csv
amino_acids_hydrate_data_update1.csv
bioactivity_preprocessed_data.csv
house_tiny.csv
inhibitor_amino_acids_data.csv
inhibitor_data.csv


In [2]:
!python --version

Python 3.11.3


In [3]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [4]:
# 创建tensor
x = range(10)
x = tf.constant(x)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [5]:
print(x.shape)

(10,)


In [6]:
len(x)

10

In [9]:
# 创建二维tensor
y = tf.reshape(x,(2,5))
z = tf.reshape(x,(2,-1))
y,z

(<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])>,
 <tf.Tensor: shape=(2, 5), dtype=int32, numpy=
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])>)

In [11]:
# 创建三维tensor
tf.zeros((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [12]:
tf.ones((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [15]:
# 将list转为tensor
tf.constant([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])>

In [16]:
# 随机数tensor
# normal 符合正态分布，均值为5，标准差为1
tf.random.normal(shape=[3,4],mean=5,stddev=1)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[5.7102156, 5.044648 , 4.1533384, 2.9156482],
       [7.2151885, 4.9477086, 3.8719401, 4.707954 ],
       [6.0803394, 3.6958656, 5.8104205, 2.0866761]], dtype=float32)>

In [30]:
# tensor基本运算
h = y + z + z*3
h

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])>

In [31]:
z/h

<tf.Tensor: shape=(2, 5), dtype=float64, numpy=
array([[nan, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2]])>

In [33]:
# 指数运算
r = tf.cast(y,tf.float32)
y,r

(<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])>,
 <tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]], dtype=float32)>)

In [38]:
# exp()里好像不能用整数
tf.exp(r) 

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[1.0000000e+00, 2.7182817e+00, 7.3890562e+00, 2.0085537e+01,
        5.4598148e+01],
       [1.4841316e+02, 4.0342877e+02, 1.0966332e+03, 2.9809580e+03,
        8.1030840e+03]], dtype=float32)>

In [42]:
# 矩阵乘法,y与转置地z相乘
tf.matmul(y,tf.transpose(z))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 30,  80],
       [ 80, 255]])>

In [43]:
# 矩阵拼接
tf.concat([y,z],axis=0)

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])>

In [44]:
tf.concat([y,z],axis=1)

<tf.Tensor: shape=(2, 10), dtype=int32, numpy=
array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])>

In [48]:
# 判断两个tensor的各个元素是否相等
tf.equal(y,z)

<tf.Tensor: shape=(2, 5), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])>

In [49]:
# 求和
tf.reduce_sum(y)

<tf.Tensor: shape=(), dtype=int32, numpy=45>

In [54]:
y = tf.cast(y,tf.float64)
y

<tf.Tensor: shape=(2, 5), dtype=float64, numpy=
array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])>

In [56]:
# L1_norm范数
tf.norm(y)

<tf.Tensor: shape=(), dtype=float64, numpy=16.881943016134134>

In [61]:
# 广播机制：当两个维度不同的tensor做运算会触发该机制
a = tf.reshape(tf.constant(range(3)),(3,1)) # 三行一列
b = tf.reshape(tf.constant(range(2)),(1,2)) # 一行两列
a,b

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]])>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]])>)

In [67]:
# 那么a中第一列的3个元素被广播（复制）到了第二列，
# 而b中第一行的2个元素被广播（复制）到了第二行和第三行。
# 如此，就可以对2个3行2列的矩阵按元素相加。
c = a+b 
c

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]])>

In [68]:
# 索引 index,左闭右开
c[1:3]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3]])>

In [70]:
c[1:3,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3])>

In [109]:
# 重新赋值
c = tf.Variable(c) # 这个必须要有
c[1,1].assign(1000)

<tf.Variable 'UnreadVariable' shape=(3, 2) dtype=float32, numpy=
array([[  10.,   10.],
       [  10., 1000.],
       [  10.,   10.]], dtype=float32)>

In [107]:
c = tf.Variable(c)
c

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[10., 10.],
       [10., 10.],
       [10., 10.]], dtype=float32)>

In [108]:
c[:,1].assign(tf.ones(c[:,1].shape,dtype = tf.float32)*10)

<tf.Variable 'UnreadVariable' shape=(3, 2) dtype=float32, numpy=
array([[10., 10.],
       [10., 10.],
       [10., 10.]], dtype=float32)>

In [110]:
# numpy to tensor
import numpy as np
p = np.ones((2,3))
p

array([[1., 1., 1.],
       [1., 1., 1.]])

In [111]:
d = tf.constant(p)
d

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [112]:
# tensor to numpy
np.array(d)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [113]:
# 使用tensorflow2.0提供的GradientTape来自动求梯度
x = tf.reshape(tf.Variable(range(4), dtype=tf.float32),(4,1))
x

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [1.],
       [2.],
       [3.]], dtype=float32)>

In [114]:
with tf.GradientTape() as t:
    t.watch(x) #对于Variable类型的变量，一般不用加此监控
    y = 2 * tf.matmul(tf.transpose(x), x)

dy_dx = t.gradient(y, x)
dy_dx

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 0.],
       [ 4.],
       [ 8.],
       [12.]], dtype=float32)>

In [115]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [117]:
# 使用dir函数,查阅可以调用的函数和类
dir(tf.dtypes)

['DType',
 'QUANTIZED_DTYPES',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'as_dtype',
 'bfloat16',
 'bool',
 'cast',
 'complex',
 'complex128',
 'complex64',
 'double',
 'experimental',
 'float16',
 'float32',
 'float64',
 'half',
 'int16',
 'int32',
 'int64',
 'int8',
 'qint16',
 'qint32',
 'qint8',
 'quint16',
 'quint8',
 'resource',
 'saturate_cast',
 'string',
 'uint16',
 'uint32',
 'uint64',
 'uint8',
 'variant']

In [118]:
dir(tf.random)

['Algorithm',
 'Generator',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'all_candidate_sampler',
 'categorical',
 'create_rng_state',
 'experimental',
 'fixed_unigram_candidate_sampler',
 'fold_in',
 'gamma',
 'get_global_generator',
 'learned_unigram_candidate_sampler',
 'log_uniform_candidate_sampler',
 'normal',
 'poisson',
 'set_global_generator',
 'set_seed',
 'shuffle',
 'split',
 'stateless_binomial',
 'stateless_categorical',
 'stateless_gamma',
 'stateless_normal',
 'stateless_parameterized_truncated_normal',
 'stateless_poisson',
 'stateless_truncated_normal',
 'stateless_uniform',
 'truncated_normal',
 'uniform',
 'uniform_candidate_sampler']

In [119]:
# 使用help函数
help(tf.ones)

Help on function ones in module tensorflow.python.ops.array_ops:

ones(shape, dtype=tf.float32, name=None)
    Creates a tensor with all elements set to one (1).
    
    See also `tf.ones_like`, `tf.zeros`, `tf.fill`, `tf.eye`.
    
    This operation returns a tensor of type `dtype` with shape `shape` and
    all elements set to one.
    
    >>> tf.ones([3, 4], tf.int32)
    <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
    array([[1, 1, 1, 1],
           [1, 1, 1, 1],
           [1, 1, 1, 1]], dtype=int32)>
    
    Args:
      shape: A `list` of integers, a `tuple` of integers, or
        a 1-D `Tensor` of type `int32`.
      dtype: Optional DType of an element in the resulting `Tensor`. Default is
        `tf.float32`.
      name: Optional string. A name for the operation.
    
    Returns:
      A `Tensor` with all elements set to one (1).



In [120]:
tf.ones([3, 4], tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])>