### 模型参数的访问、初始化和共享

In [2]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.13.0


In [4]:
# 定义一个含单隐藏层的多层感知机
net = tf.keras.models.Sequential()
net.add(tf.keras.layers.Flatten())
net.add(tf.keras.layers.Dense(256,activation=tf.nn.relu))
net.add(tf.keras.layers.Dense(10))

In [5]:
X = tf.random.uniform((2,20))

In [6]:
Y = net(X)
Y

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[ 0.24136473,  0.34850952, -0.23637363, -0.27474785, -0.01037002,
        -0.3767209 ,  0.2055873 , -0.07725191,  0.27190816,  0.3784794 ],
       [ 0.1918543 ,  0.26263705, -0.18291003, -0.13598111, -0.02713746,
        -0.24704617,  0.1230057 ,  0.09265482,  0.22287282,  0.34347668]],
      dtype=float32)>

In [9]:
# 对于使用Sequential类构造的神经网络，我们可以通过weights属性来访问网络任一层的权重
net.weights[0],type(net.weights[0]) # 索引0表示隐藏层为Sequential实例最先添加的层

(<tf.Variable 'dense_2/kernel:0' shape=(20, 256) dtype=float32, numpy=
 array([[ 0.01227216, -0.02028386, -0.01541623, ..., -0.12315158,
         -0.01280665,  0.00726815],
        [-0.10589084, -0.11762962,  0.04995589, ...,  0.13865083,
          0.04262722,  0.04940568],
        [ 0.06251332,  0.10339081,  0.07426971, ...,  0.12324575,
         -0.13324833,  0.12726563],
        ...,
        [ 0.0130284 , -0.02520143, -0.00392789, ...,  0.08796285,
          0.14008462, -0.04218925],
        [ 0.06036122, -0.05582738, -0.06013231, ..., -0.09222677,
          0.12349492, -0.05088478],
        [ 0.08322953,  0.14061606, -0.11439008, ...,  0.01000005,
         -0.08003447,  0.11637786]], dtype=float32)>,
 tensorflow.python.ops.resource_variable_ops.ResourceVariable)

In [10]:
# 将权重参数初始化成均值为0、标准差为0.01的正态分布随机数，并依然将偏差参数清零
class Linear(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.d1 = tf.keras.layers.Dense(
            units=10,
            activation=None,
            kernel_initializer=tf.random_normal_initializer(mean=0,stddev=0.01),
            bias_initializer=tf.zeros_initializer()
        )
        self.d2 = tf.keras.layers.Dense(
            units=1,
            activation=None,
            kernel_initializer=tf.ones_initializer(),
            bias_initializer=tf.ones_initializer()
        )

    def call(self, input):
        output = self.d1(input)
        output = self.d2(output)
        return output

net = Linear()
net(X)
net.get_weights()


[array([[-1.11397298e-03,  1.52313365e-02,  4.67497902e-03,
          2.23250575e-02, -2.01039128e-02,  4.03461745e-03,
         -1.36750145e-02, -1.73530809e-03, -1.08454050e-02,
         -2.77151749e-03],
        [ 1.68593582e-02, -9.19748843e-03,  1.94303284e-03,
          9.44082160e-03, -2.38404679e-03,  1.28073152e-02,
          4.75913694e-04, -4.01601288e-03, -6.66517531e-03,
         -7.66067882e-04],
        [-1.28989611e-02,  9.11561679e-03, -5.33284526e-03,
          1.74852414e-03,  1.08626038e-02,  2.77836644e-03,
         -9.22966655e-03,  1.10750757e-02, -5.03025716e-03,
          2.11262540e-03],
        [-2.46548280e-03,  7.91387353e-03,  3.49791581e-03,
          5.33504412e-03, -2.70357728e-02,  1.30553381e-03,
          7.15524657e-03,  2.28591394e-02,  4.47319122e-03,
          4.74378141e-03],
        [-4.23650112e-04,  1.22611206e-02, -1.87716098e-03,
         -1.30425615e-03,  3.41825769e-03,  1.90274157e-02,
         -1.01847118e-02,  1.06417201e-02, -2.420178

In [11]:
# 使用tf.keras.initializers类中的方法实现自定义初始化
def my_init():
    return tf.keras.initializers.Ones()

In [12]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(64, kernel_initializer=my_init()))

In [13]:
Y = model(X)
model.weights[0]

<tf.Variable 'dense_6/kernel:0' shape=(20, 64) dtype=float32, numpy=
array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)>